version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql


  backend:
    build: .
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
    entrypoint: ["/bin/sh", "-c", "sleep 40 && java -jar target/backend-0.0.1-SNAPSHOT.jar"]
    volumes:
      - ./uploads:/app/uploads

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql_data:
